base_dir: data
exp_name: 3dgs-e10
lambda: 0.2

n_points: 1000

lr: 
  default: 0.001
  xyz: 0.001
  sh_coeffs: 0.01
  opacity_logit: 0.05
  scale_log: 0.005
  rot_quat: 0.001

iters:
  total: 20000
  start: 500
  densify: 100
  reset: 1000

renderer: cuda
seed: 42

