exp_name: 3dgs-e1
seed: 42
base_dir: data

n_iters: 5000 # 학습 횟수 (100번은 너무 적어서 1000번으로 늘림)
lambda = 0.2

lr: 
  default: 0.001
  xyz: 0.001
  sh_coeffs: 0.01
  opacity_logit: 0.05
  scale_log: 0.005
  rot_quat: 0.001